method: grid
metric:
  name: test/new_caption/image_to_text_R@1
  goal: maximize
parameters:
  batch_size:
    values: [64]
  group_size:
    values: [3]
  learning_rate:
    values: [1.8748186634898305e-05]
  num_epochs:
    values: [7]
  alpha:
    values: [0.7]
  tau:
    values: [0.1]
  loss:
    values: [1]